### PR TITLE
refactor!: remove nvim-treesitter dependency

### PR DESCRIPTION
**Pull request by amaanq**
The 1.0 rewrite of nvim-treesitter removes its plugin functionality in favor of using vim.treesitter, so I moved stripped-down versions of the used functions here, and removed usage of nvim-treesitter, seems to be okay for me so far but do thoroughly review my PR, thanks :)

### CODE REVIEW

**Review by bennypowers — CHANGES_REQUESTED** [review]
please revert whitespace, formatting changes

**Comment by bennypowers** [comment]
I'm concerned that upstream changes / fixes to ts-utils won't be reflected here. In other words I'm concerned that this adds maintenance burden. What do you think?

One way to deal with that would be to explicitly change the private apis of these local plugins so that it's clear they aren't copies of ts-utils functions. That's not an amazing solution, though

**Comment by amaanq** [comment]
> please revert whitespace, formatting changes (e.g. parens around require calls)

Done, sorry about that

> I'm concerned that upstream changes / fixes to ts-utils won't be reflected here. In other words I'm concerned that this adds maintenance burden. What do you think?
> 
> One way to deal with that would be to explicitly change the private apis of these local plugins so that it's clear they aren't copies of ts-utils functions. That's not an amazing solution, though

The thing is that really won't be updated at all except for important performance/security fixes (which, if any, would stem from upstream and be in `:h news`), since after 1.0 becomes the default (with 0.10's release I believe), the master branch shouldn't even be considered usable and will be kept around for legacy support only. The current stuff is not great as well, I refactored some bits using new vim.treesitter/TSNode apis that might be slightly better in performance - and stripped out unneeded code as well for the purposes that nvim-regexplainer uses at least

So imo this doesn't add maintenance burden, it is good as is and has been working fine for years in nvim-treesitter, unless `vim.treesitter`'s api changes, which, again, will be in the news :)

**Comment by bennypowers** [comment]
nightly is failing

**Comment by amaanq** [comment]
not sure why, nightly fails for me locally w/o my changes as well

**Comment by bennypowers** [comment]
ok then. if you're able to run this occasionally on nightly and figure it out, I'd be grateful

**Review by bennypowers — APPROVED** [review]
walla ahla PR habibi shukran

**Pull request merged**
